const simpleStatistics = require('simple-statistics');
const Product = require('../models/Product');
const PurchaseOrder = require('../models/PurchaseOrder');
const Supplier = require('../models/Supplier');

// @desc    Run AI analysis to predict demand and reorder
// @route   POST /api/ai/predict-reorder
// @access  Admin
const predictAndReorder = async (req, res) => {
    try {
        const products = await Product.find().populate('supplier');
        const alerts = [];
        const generatedOrders = [];

        for (const product of products) {
            if (!product.supplier) continue;

            // Mock sales history for now (in real app, query Orders)
            // Representing [Day, Sales] typically. 
            // Here we pretend we have last 7 days sales data
            // If no data, random mock for demo
            const salesHistory = [
                [1, Math.floor(Math.random() * 5)],
                [2, Math.floor(Math.random() * 5)],
                [3, Math.floor(Math.random() * 5)],
                [4, Math.floor(Math.random() * 5)],
                [5, Math.floor(Math.random() * 5)],
                [6, Math.floor(Math.random() * 6)],
                [7, Math.floor(Math.random() * 8)] // Trend going up?
            ];

            // Linear Regression to predict next day demand
            const line = simpleStatistics.linearRegression(salesHistory);
            const prediction = simpleStatistics.linearRegressionLine(line)(8); // Predict for Day 8

            // Logic: If (CurrentStock - Prediction * LeadTime) < ReorderLevel
            // Then reorder
            const predictedConsumptionDuringLeadTime = prediction * product.leadTime;
            const projectedStock = product.quantity - predictedConsumptionDuringLeadTime;

            if (projectedStock < product.reorderLevel) {
                // Needs reorder
                const reorderQty = Math.ceil(product.reorderLevel * 2 - projectedStock); // Simple formula to top up

                alerts.push({
                    product: product.name,
                    currentStock: product.quantity,
                    predictedDemand: prediction.toFixed(2),
                    message: `Stock projected to fall below reorder level (${product.reorderLevel})`
                });

                // Check if pending order exists? (Skipped for simplicity)

                // Create Auto Order
                const order = await PurchaseOrder.create({
                    orderNumber: `ORD-AI-${Date.now()}-${product.sku}`,
                    supplier: product.supplier._id,
                    items: [{
                        product: product._id,
                        quantity: reorderQty,
                        unitPrice: product.price // Assuming cost price same as price for demo (or add costPrice field)
                    }],
                    totalAmount: reorderQty * product.price,
                    status: 'Pending',
                    isAutoGenerated: true,
                    createdBy: req.user._id
                });
                generatedOrders.push(order);
            }
        }

        res.json({
            success: true,
            alerts,
            generatedOrders
        });

    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'AI Analysis Failed' });
    }
};

module.exports = { predictAndReorder };
